= Table.AddColumn(#"Changed Type", "YearMonth", each Date.ToText([Date], "MMM") & " " & Date.ToText([Date], "yy"))
