= Table.AddColumn(#"Added Uniqueidentifier", "DateCategory", each Text.From([Date]) &"_" & [Category])

// text.from is essential
